config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /flats
  # GET /flats.json
  def index
    @flats = Flat.all

    flats = @flats.map do |flat|
      flat.as_json.transform_keys { |key| key.camelize(:lower) }
    end
    @flats_props = { flats: flats }
  end

  # GET /flats/1
  # GET /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  # POST /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: 'Flat was successfully created.' }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1
  # PATCH/PUT /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: 'Flat was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1
  # DELETE /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_params
      params.require(:flat).permit(:name, :image_url, :price, :price_currency, :lat, :lng)
    end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_with(model: flat, local: true) do |form| %>
  <% if flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
      <% flat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :flat_name %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :flat_image_url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :flat_price %>
  </div>

  <div class="field">
    <%= form.label :price_currency %>
    <%= form.text_field :price_currency, id: :flat_price_currency %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat, id: :flat_lat %>
  </div>

  <div class="field">
    <%= form.label :lng %>
    <%= form.text_field :lng, id: :flat_lng %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flats</h1>

<%= react_component("Flats", props: @flats_props, prerender: true) %>
<%= javascript_pack_tag 'flats-bundle' %>
<%= stylesheet_pack_tag 'flats-bundle' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Price currency</th>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.name %></td>
        <td><%= flat.image_url %></td>
        <td><%= flat.price %></td>
        <td><%= flat.price_currency %></td>
        <td><%= flat.lat %></td>
        <td><%= flat.lng %></td>
        <td><%= link_to 'Show', flat %></td>
        <td><%= link_to 'Edit', edit_flat_path(flat) %></td>
        <td><%= link_to 'Destroy', flat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flat', new_flat_path %>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flat.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @flat.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @flat.price %>
</p>

<p>
  <strong>Price currency:</strong>
  <%= @flat.price_currency %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @flat.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @flat.lng %>
</p>

<%= link_to 'Edit', edit_flat_path(@flat) %> |
<%= link_to 'Back', flats_path %>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: true) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>